src/Entity/Categories/Categories.php
<?php

namespace App\Entity\Categories;

use App\Entity\Fields\Fields;
use App\Entity\Games\Games;
use App\Entity\Runs\Runs;
use App\Repository\Categories\CategoriesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: CategoriesRepository::class)]
class Categories
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $rules = null;

    #[ORM\Column]
    private ?int $players = null;

    #[ORM\ManyToOne(inversedBy: 'refCategories')]
    private ?Games $refGames = null;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'refCategories')]
    private ?self $refCategories = null;

    #[ORM\OneToMany(targetEntity: Fields::class, mappedBy: 'refCategories')]
    private Collection $refFields;

    #[ORM\OneToMany(targetEntity: Runs::class, mappedBy: 'refCategories')]
    private Collection $refRuns;

    #[ORM\Column(type: 'uuid')]
    private ?Uuid $uuid = null;

    #[ORM\Column]
    private ?bool $videoMandatory = null;

    public function __construct()
    {
        /*$this->refCategories = new ArrayCollection();*/
        $this->refFields = new ArrayCollection();
        $this->refRuns = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getRules(): ?string
    {
        return $this->rules;
    }

    public function setRules(string $rules): static
    {
        $this->rules = $rules;

        return $this;
    }

    public function getPlayers(): ?int
    {
        return $this->players;
    }

    public function setPlayers(int $players): static
    {
        $this->players = $players;

        return $this;
    }

    public function getRefGames(): ?Games
    {
        return $this->refGames;
    }

    public function setRefGames(?Games $refGames): static
    {
        $this->refGames = $refGames;

        return $this;
    }

    public function getRefCategories(): ?self
    {
        return $this->refCategories;
    }

    public function setRefCategories(?self $refCategories): static
    {
        $this->refCategories = $refCategories;

        return $this;
    }

    public function addRefCategory(self $refCategory): static
    {
        if (!$this->refCategories->contains($refCategory)) {
            $this->refCategories->add($refCategory);
            $refCategory->setRefCategories($this);
        }

        return $this;
    }

    public function removeRefCategory(self $refCategory): static
    {
        if ($this->refCategories->removeElement($refCategory)) {
            // set the owning side to null (unless already changed)
            if ($refCategory->getRefCategories() === $this) {
                $refCategory->setRefCategories(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Fields>
     */
    public function getRefFields(): Collection
    {
        return $this->refFields;
    }

    public function addRefField(Fields $refField): static
    {
        if (!$this->refFields->contains($refField)) {
            $this->refFields->add($refField);
            $refField->setRefCategories($this);
        }

        return $this;
    }

    public function removeRefField(Fields $refField): static
    {
        if ($this->refFields->removeElement($refField)) {
            // set the owning side to null (unless already changed)
            if ($refField->getRefCategories() === $this) {
                $refField->setRefCategories(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Runs>
     */
    public function getRefRuns(): Collection
    {
        return $this->refRuns;
    }

    public function addRefRun(Runs $refRun): static
    {
        if (!$this->refRuns->contains($refRun)) {
            $this->refRuns->add($refRun);
            $refRun->setRefCategories($this);
        }

        return $this;
    }

    public function removeRefRun(Runs $refRun): static
    {
        if ($this->refRuns->removeElement($refRun)) {
            // set the owning side to null (unless already changed)
            if ($refRun->getRefCategories() === $this) {
                $refRun->setRefCategories(null);
            }
        }

        return $this;
    }

    public function getUuid(): ?Uuid
    {
        return $this->uuid;
    }

    public function setUuid(Uuid $uuid): static
    {
        $this->uuid = $uuid;

        return $this;
    }

    public function getPrimaryComparison()
    {

        foreach ($this->getRefFields() as $field){
            if (array_key_exists('primary', $field->getConfig())) {
                return $field;
            }
        }
        return null;
    }

    public function getSecondaryComparison()
    {

        foreach ($this->getRefFields() as $field){
            if (array_key_exists('secondary', $field->getConfig())) {
                return $field;
            }
        }
        return null;
    }

    /**
     * @return Fields[]
     */
    public function getSubCategories(): array
    {
        $subCategories = [];
        foreach ($this->getRefFields() as $field){
            if (array_key_exists('subCategory', $field->getConfig())) {
                $subCategories[] = $field;
            }
        }
        return $subCategories;
    }

    /**
     * Renvoie les informations secondaire (Liste qui n'est pas une subcatégorie) de la catégorie
     * @return Fields[]
     */
    public function getConfigLeaderboard(): array
    {
        //Possible de criteria sur order
        //Pour l'ordre des champs à afficher
        $subCategories = [];
        foreach ($this->getRefFields() as $field){
            if (!array_key_exists('subCategory', $field->getConfig()) && !array_key_exists('secondary', $field->getConfig()) && !array_key_exists('primary', $field->getConfig())) {
                $subCategories[] = $field;
            }
        }
        return $subCategories;
    }

    public function isVideoMandatory(): ?bool
    {
        return $this->videoMandatory;
    }

    public function setVideoMandatory(bool $videoMandatory): static
    {
        $this->videoMandatory = $videoMandatory;

        return $this;
    }
}

src/Form/Runs/RunsSubmitType.php
<?php

namespace App\Form\Runs;

use App\Entity\Categories\Categories;
use App\Entity\Runs\Runs;
use App\Entity\Status\Status;
use App\Entity\Users\Users;
use App\Repository\Categories\CategoriesRepository;
use Doctrine\ORM\Query\Expr\Join;
use Doctrine\ORM\QueryBuilder;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use function Sodium\add;

class RunsSubmitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        /* @var $category Categories */
        $category = $options['category'];

        $builder
            ->add('refCategories', EntityType::class, [
                'class' => Categories::class,
                'query_builder' => function (CategoriesRepository $categoriesRepository) use ($category, $options): QueryBuilder {
                    return $categoriesRepository->createQueryBuilder('c')
                        ->join('c.refGames', 'g', 'WITH', 'g.id = c.refGames')
                        ->where('g.id = :id')
                        ->setParameter('id', $category->getRefGames()->getId());
                },
                'choice_label' => 'name',
                'choice_value' => 'uuid'
            ])

        ;
        /*if ($category !== null) {
            $fields = $category->getRefFields();

            foreach ($fields as $field) {
                switch ($field->getRefFieldTypes()->getBackName()) {
                    case 'time-goal':
                        $builder
                            ->add('hours', IntegerType::class, [
                                'mapped' => false,
                                'required' => true
                            ])
                            ->add('minutes', IntegerType::class, [
                                'mapped' => false
                            ])
                            ->add('secondes', IntegerType::class, [
                                'mapped' => false
                            ])
                            ->add('milliseconds', IntegerType::class, [
                                'mapped' => false
                            ]);
                        break;
                }
            }
        }*/
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Runs::class,
            'category' => null,
            'allow_extra_fields' => true,
        ]);
    }
}

src/Form/Runs/RunsType.php
<?php

namespace App\Form\Runs;

use App\Entity\Categories\Categories;
use App\Entity\Games\Games;
use App\Entity\Runs\Runs;
use App\Entity\Status\Status;
use App\Entity\Users\Users;
use App\Repository\Categories\CategoriesRepository;
use Doctrine\ORM\Query\Expr\Join;
use Doctrine\ORM\QueryBuilder;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RunsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {


        $builder
            ->add('refCategories', EntityType::class, [
                'attr' => ['class' => 'form-select'],
                'class' => Categories::class,
                'query_builder' => function (CategoriesRepository $categoriesRepository) use ($options): QueryBuilder {
                    return $categoriesRepository->createQueryBuilder('c')
                        ->join('c.refGames', 'g', 'WITH', 'g.id = c.refGames')
                        ->where('g.id = :id')
                        ->setParameter('id', $options['game']->getId());
                },
                'choice_label' => 'name',
                'choice_value' => 'uuid',
                'label' => 'Category *',
            ])
            ->add('game', HiddenType::class, [
                'data' => $options['game']->getUuid(),
                'mapped' => false
            ])
            ->add('dateMade', DateType::class, [
                'attr' => ['class' => 'form-control'],
                'label' => 'Date *',
            ])
            ->add('description', TextareaType::class, [
                'attr' => [
                    'class' => 'form-control',
                ],
                'required' => false,
                'label' => 'Description',
            ])
            ->add('video', UrlType::class, [
                'attr' => [
                    'class' => 'form-control',
                ],
                'required' =>false,
                'label' => 'Video',
            ])
            ->add('modNotes', TextareaType::class, [
                "attr"=>[
                    "class"=>"form-control",
                ],
                'help' => 'Required if the run is rejected',
                "label" => "Mod Notes",
                'required' => false
            ])
            ->add('uuid' , HiddenType::class, [
                'data' => $options['uuid'],
                'mapped' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Runs::class,
            'game' => null,
            'uuid' => null
        ]);

        $resolver->setDefined(['game']);
    }
}

src/Controller/Runs/RunsAjaxController.php
<?php

namespace App\Controller\Runs;

use App\Entity\Categories\Categories;
use App\Entity\Games\Games;
use App\Entity\Runs\Runs;
use App\Entity\Status\Status;
use App\Form\Runs\RunsSubmitType;
use App\Form\Runs\RunsType;
use App\Repository\Runs\RunsRepository;
use App\Service\Categories\CategoriesService;
use App\Service\Mailer\MailerService;
use App\Service\Runs\RunsService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use function Symfony\Component\Clock\now;

#[Route('/runs')]
class RunsAjaxController extends AbstractController
{
    public function __construct(
        private CategoriesService $categoriesService,
        private EntityManagerInterface $entityManager,
        private RunsService $runsService,
        private MailerService $mailerService
    ) {}

    #[Route('/fields/call', name: 'app_runs_fields_call', methods: ['POST'])]
    public function loadFieldsCall(Request $request): Response
    {
        $category = $this->entityManager->getRepository(Categories::class)->findOneBy(['uuid' => $request->request->all()['runs']['refCategories']]);

        if (!$category instanceof Categories){
            return new JsonResponse(['message' => 'An error occurred'], 400);
        }

        $game = $this->entityManager->getRepository(Games::class)->findOneBy(['uuid' => $request->request->all()['runs']['game']]);
        if (!$game instanceof Games){
            return new JsonResponse(['message' => 'An error occurred'], 400);
        }

        //Gestion d'erreur si le user change l'uuid par un autre correspondant
        if ($category->getRefGames() !== $game){
            return new JsonResponse(['message' => 'An error occurred'], 400);
        }


        return $this->categoriesService->getFieldsFromCategory($category);
        //Return les fields en fonction de la category donc category->getFields ?
        /*return $this->categoriesService->getFieldsFromCategory()*/
    }
    #[Route('/submit/call', name: 'app_runs_submit_call', methods: ['POST'])]
    public function submitCall(Request $request): Response
    {

        $game = $this->entityManager->getRepository(Games::class)->findOneBy(['uuid' => $request->request->all()['runs']['game']]);

        if (!$game instanceof Games){
            return new JsonResponse(['An error occurred'], 400);
        }

        $run = new Runs();
        $form = $this->createForm(RunsType::class,$run , ['game' => $game]);
        $form->handleRequest($request);


        return $this->runsService->runsValidation($run, $request);
    }


    #[Route('/validation/call', name: 'app_runs_validation_call', methods: ['POST'])]
    public function validationCall(Request $request): Response
    {


        $run = $this->entityManager->getRepository(Runs::class)->findOneBy(['uuid' => $request->request->all()['runs']['uuid']]);

        $modnote = trim(htmlspecialchars($request->request->all()['runs']['modNotes']));

        if ($modnote === ""){
            $run->setModNotes(null);
        }else{
            $run->setModNotes($modnote);
        }


        $this->runsService->checkOldAndNewRun($run);

        $run->setDateCheck(now());
        $run->setVerifiedBy($this->getUser());

        $emailTo = [];
        foreach ($run->getRefUsers() as $user){
            $emailTo[] = $user->getEmail();
        }

        $this->mailerService->sendMailRunChecked($emailTo,$run);

        $this->entityManager->persist($run);
        $this->entityManager->flush();

        return new JsonResponse(['message' => 'Run validated successfully', 'url' => '/' .$run->getRefGame()->getRewrite() .'/runs/verifications'], 200);

    }

    #[Route('/reject/call', name: 'app_runs_reject_call', methods: ['POST'])]
    public function rejectCall(Request $request): Response
    {

        $run = $this->entityManager->getRepository(Runs::class)->findOneBy(['uuid' => $request->request->all()['runs']['uuid']]);

        $modnote = $request->request->all()['runs']['modNotes'];


        if ($modnote === null || empty(trim($modnote))){
            return new JsonResponse(['message' => 'Please fill the reason of the reject'], 400);
        }

        $run->setModNotes($modnote);

        $run->setRefStatus($this->entityManager->getRepository(Status::class)->find(3));

        $run->setDateCheck(now());
        $run->setVerifiedBy($this->getUser());

        $emailTo = [];
        foreach ($run->getRefUsers() as $user){
            $emailTo[] = $user->getEmail();
        }

        $this->mailerService->sendMailRunChecked($emailTo,$run);

        $this->entityManager->persist($run);
        $this->entityManager->flush();


        return new JsonResponse(['message' => 'Run rejected successfully', 'url' => '/' .$run->getRefGame()->getRewrite() .'/runs/verifications'], 200);
    }

}

templates/runs/_delete_form.html.twig
<form method="post" action="{{ path('app_runs_runs_delete', {'id': run.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ run.id) }}">
    <button class="btn">Delete</button>
</form>

templates/runs/edit.html.twig
{% extends '../base.html.twig' %}

{% block title %}Edit Runs{% endblock %}

{% block body %}
    <h1>Edit Runs</h1>

    {{ include('runs/runs/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_runs_runs_index') }}">back to list</a>

    {{ include('runs/runs/_delete_form.html.twig') }}
{% endblock %}

templates/runs/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Runs Verifications - {{ game.name }} - Hub Speedrun{% endblock %}

{% block body %}

    {{ include('games/includes/cardGame.html.twig') }}

    <div class="container mt-4">

        <div class="mb-2">
            <a class="btn btn-primary" href="{{ path('app_games_show', {'rewrite' : game.rewrite}) }}">Return</a>
        </div>

        <div class="overflow-x-auto">
            <table id="tableVerif" class="table"
                   style="white-space: nowrap" {{ stimulus_controller('linkLeaderboard') }}>
                <thead>
                    <tr>
                        <th>Runner</th>
                        <th>Categories</th>
                        <th>Times</th>
                        <th>Submission date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for run in runs %}
                        <tr class="rowLeaderboard"
                            data-href="{{ path('app_runs_verification', {'rewrite' : game.rewrite, 'uuid' : run.uuid} ) }}">
                            <td class="align-middle">
                                {% for user in run.getRefUsers %}
                                    {% if loop.first %}
                                        {{ user.username }}
                                    {% else %}
                                        · {{ user.username }}
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td id="categories" class="align-middle">
                                <span>{{ run.refCategories().getName() }}</span> <br>
                                <span class="subCategories">
                                {% for subCategorie in run.refCategories.subCategories %}
                                    {% if loop.first %}
                                        {% if run.getDataFromField(subCategorie) is not null %}
                                            {{ run.getDataFromField(subCategorie).data }}
                                        {% else %}
                                            ---
                                        {% endif %}
                                    {% else %}
                                        {% if run.getDataFromField(subCategorie) is not null %}

                                            · {{ run.getDataFromField(subCategorie).data }}
                                        {% else %}
                                            ---
                                        {% endif %}

                                    {% endif %}
                                {% endfor %}
                            </span>
                            </td>
                            <td class="align-middle">
                                {% set primaryComparison = run.refCategories.primaryComparison %}
                                {% set secondaryComparison = run.refCategories.secondaryComparison %}
                                <span>{{ primaryComparison.config['label'] }} {{ run.primaryComparisonData(primaryComparison).data | formatTimer }}</span>
                                <br>

                                {% if secondaryComparison is not null %}
                                    {% if run.secondaryComparisonData(secondaryComparison) is not null %}
                                        <span>{{ secondaryComparison.config['label'] }} {{ run.secondaryComparisonData(secondaryComparison).data | formatTimer }}</span>
                                    {% else %}
                                        <span>---</span>
                                    {% endif %}
                                {% endif %}

                            </td>
                            <td class="align-middle">
                                <span>{{ run.dateSubmitted | date('Y-m-d') }}</span>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="4" class="text-start text-sm-center">No runs to be verified</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

templates/runs/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Submit Run - {{ game.name }} - Hub Speedrun{% endblock %}

{% block body %}

    {{ include('games/includes/cardGame.html.twig') }}

    <div class="container">

        {{ form_start(form, {'attr' : {'id' : 'formRuns', 'data-controller' : 'loadFields runsValidation', 'data-action' : 'submit->runsValidation#submitRun'} }) }}

        <div class="row mt-3">
            <div class="col-12 col-md-6">
                {{ form_label(form.refCategories) }}
                {{ form_widget(form.refCategories) }}
            </div>
        </div>
        {{ form_widget(form.game) }}

        <div id="loadFields" class="mt-3"></div>

        <div class="row mt-3">
            <div class="col-12 col-md-6">

                {{ form_label(form.dateMade) }}
                {{ form_widget(form.dateMade) }}
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-12">
                {{ form_label(form.description) }}
                {{ form_widget(form.description) }}
            </div>
        </div>

        <div class="mt-3">
            <div class="col-12 col-md-6">
                {{ form_label(form.video) }}
                {{ form_widget(form.video) }}
            </div>
        </div>
        <div class="d-flex justify-content-between mt-3">
            <a class="btn btn-primary" href="{{ path('app_games_show', {rewrite : game.rewrite}) }}">Back to game</a>
            <button class="btn btn-validation">{{ button_label|default('Save') }}</button>
        </div>
        {{ form_end(form, {render_rest: false}) }}
    </div>

{% endblock %}

templates/runs/show.html.twig
{% extends '/base.html.twig' %}

{% block title %}Run Verification - {{ game.name }} - Hub Speedrun{% endblock %}

{% block body %}

    {% include 'games/includes/cardGame.html.twig' %}

    <div class="container mt-4">
        <h1></h1>

        {% set primaryComparison = run.refCategories.primaryComparison %}
        {% set secondaryComparison = run.refCategories.secondaryComparison %}

        <p><strong>{{ run.refCategories.name }}</strong> in
            <strong>{{ run.primaryComparisonData(primaryComparison).data|formatTimer }}</strong> by
            {% for user in run.refUsers %}
                <strong>
                    {% if loop.first %}
                        {{ user.username }}
                    {% else %}
                        · {{ user.username }}
                    {% endif %}
                </strong>
            {% endfor %}
        </p>

        <div>
            <div>

                {% if run.video is not null %}
                    <div>
                        {% if typeLink is same as 'youtube' %}
                            {{ include('runs/includes/show/youtube.html.twig') }}
                        {% elseif typeLink is same as 'twitch' %}
                            {{ include('runs/includes/show/twitch.html.twig') }}
                        {% endif %}
                    </div>
                {% endif %}

            </div>


            <div id="detailRun" class="row mt-4">

                {% if run.modNotes is not null %}
                    <div id="modnote" class="mb-3">
                        <div class="col-12 infoCard">
                            <span><strong>Mod Note</strong></span>
                            <span>{{ run.modNotes }}</span>
                        </div>
                    </div>

                {% endif %}

                {% if run.description is not null %}
                    <div id="description" class="mb-3">
                        <div class="col-12 infoCard">
                            <span><strong>Description</strong></span>
                            <span>{{ run.description }}</span>
                        </div>
                    </div>
                {% endif %}

                <div id="primaryInfo"
                     class=" col-12 {% if run.refCategories.configLeaderboard is not empty %} col-md-3 {% else %} col-md-4 {% endif %}">
                    <div class="infoCard">
                        <span><strong>Category</strong></span>
                        <span>{{ run.refCategories.name }}</span>
                    </div>

                    {% for subCategorie in run.refCategories.subCategories %}
                        <div class="infoCard">
                            <span><strong>{{ subCategorie.config['label'] }}</strong></span>
                            <span>{{ run.getDataFromField(subCategorie).data }}</span>
                        </div>
                    {% endfor %}
                </div>

                <div id="times"
                     class="col-12 {% if run.refCategories.configLeaderboard is not empty %} col-md-3 {% else %} col-md-4 {% endif %}">
                    <div class="infoCard">
                        <span><strong>{{ primaryComparison.config['label'] }}</strong></span>
                        <p>{{ run.primaryComparisonData(primaryComparison).data|formatTimer }}</p>
                    </div>
                    {% if secondaryComparison is not null %}
                        <div class="infoCard">
                            <span><strong>{{ secondaryComparison.config['label'] }}</strong></span>
                            {% if run.secondaryComparisonData(secondaryComparison) is null %}
                                <span>---</span>
                            {% else %}
                                <span>{{ run.secondaryComparisonData(secondaryComparison).data|formatTimer }}</span>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>

                {% if run.refCategories.configLeaderboard is not empty %}
                    <div id="secondaryInfo" class=" col-12 col-md-3">
                        {% for field in run.refCategories.configLeaderboard %}
                            <div class="infoCard">
                                <span><strong>{{ field.config['label'] }}</strong></span>
                                <span>{{ run.dataFromField(field).data }}</span>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}


                <div id="player"
                     class="col-12 {% if run.refCategories.configLeaderboard is not empty %} col-md-3 {% else %} col-md-4 {% endif %}">
                    <div class="infoCard">
                        <span><strong>{% if run.refUsers|length > 1 %}Players{% else %}Player{% endif %}</strong></span>
                        {% for user in run.refUsers %}
                            {% if loop.first %}
                                {{ user.username }}
                            {% else %}
                                · {{ user.username }}
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div id="date" class="infoCard">
                        <span><strong>Date done</strong></span>
                        <span>{{ run.dateMade|date('Y-m-d') }}</span>
                    </div>
                    {% if run.refStatus.id != 1 %}
                        <div class="infoCard">
                            <span><strong>Verified by {{ run.verifiedBy.username }}</strong></span>
                            <span>{{ run.dateCheck|date('Y-m-d') }}</span>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>


    </div>
{% endblock %}